[gcp_service_account]
type = "service_account"
project_id = "abiding-octane-463319-v3"
private_key_id = "7a0b26d708b073371227207935853fffb413e815"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDc81sSe0Mn/ngy
Xmxk0trbi/3Dnnnet9W/p8Joj8964OuXeVzj7JOhgjg7hhJ3oJB3hF1h3eLSZpWu
usD5x4AyOJ4QgkcB4NrO4gfQCASaidj2lRZ2zrOeka4VHLmtaVNqA7jstcBxnR8w
Ds1sSOiAqwQGfF7s8P+4PJr2LORuYIu/7U/2VdnDw5SwrNVJ3BK7h0mccu6YCsdo
upi9kU2VUKIXRA+NBzeBnGIJmWODfwDsfIl6LpzrwTIQCnLGEPIR3BI31yiN46JO
awKBAAmr/aF6Ki32Mn4GYwXCUkEjPlpbBbF6x6rYsdoUJB7uB9XJfZ9lcRQpPilA
kJRoAA5NAgMBAAECggEACwgymKhjaMSNq1QoHNujVll1zPXld1+d8lEVxaNClIvU
7439e5rlHygRlzVBSExR0knfYMLTr7Y0DJKiDoatybQmfkQG+BrKShCim7o+wpmV
5e/5PGrjMIxtEPxLcBNleRJhAh6sEnAqLbvbeWflhgEj9Q/yLGn3FrOd+CMzL6iW
KRL+RR8JR2coQVGA0x/b7jI344V8nc3/eNPxQcOJ5dCvKtt6cZ2WoAVz2wu0Di1D
XtuMR55jfAicA2A42GtopwG95S+Bj+oZVLcKQn7QJrYoYN1iUXn/+L97JUKMTPoW
9JdEyAso5kQR04BD++D4sbjLx8mtXebk6dlid97IoQKBgQDxUavmEgVhayi92T/B
8Wti5IBQWFPpRiqLmoMb1zCtk6SoM/+E6QsymxktTjkJRTYbmFxM16YXtaS2oYVW
1BRRqqNEFvbn16Qr62T5j0/3h/XU8jChqg1wg4Em4WnP6sJY9xSU53NwRqAWjnPu
SkRqDpaSZwn/7MekoEMVYar/7QKBgQDqZHbcAZbAU2hEs/dNnpnzaPDdtYfS0Rgr
J8gJlkM8VCmo6abllG7Y564RbdyeZOhBB06PWpqVkXsVH3JL1S1NRFuHbjK2EY2y
Sgm7w4s2G1KGS47SsvU8jKVJePqgeMgNxru/KOCQmCKJpLNhExfjS4mowBfG9Giv
ZqQJcG+74QKBgELz/PSFVXbU62XZC8Z8e+XhLfScvRNAw3ceNHgZ+Uh/aTS90IwI
uHGe9JpMVKjMyhlX6WvsfQmg/QUqxTr09no+FLREhtaGTudclRRkfbRYxY0CcRm5
e6cW5VNrQRdNtARI8S3rFW02Ox5nAaVAd8DRMVeHPRADmtSDHnmlMnN1AoGAGNE4
UIUOjCCIqrWPWrWPQVl8H01oKycecvtMT8+MIOgcXRkYJbi4n9iv8oJ6WH8ApFn8
tGr4cRutN4hT1rmkiUjSlB1T2zkyko0KSMokhD8SVsvLPH3cP2P44DWh+7muHN9M
46mVVVn2VjKNF5so7VUDJ03ndpZMOz4X4jP4cKECgYB8H+Hsuf7XAd54v17XlxmQ
2ELSkpdjFqtB6e3XB6W5qmEYbOtW0d2Oeagf2ebnE+7bAvHr6BtxuqMVSOM50KKu
vb+JrPuR3i8sqKc0I0GMnCkVvIBRtwYAshlomlLWFecn9s0oTVXlP8TUflujKUNa
ExWEx+CFPXg2CWmVUniMtA==
-----END PRIVATE KEY-----"""
client_email = "hyojoowoo@abiding-octane-463319-v3.iam.gserviceaccount.com"
client_id = "107439014498691337989"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/hyojoowoo@abiding-octane-463319-v3.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
